<a href="https://colab.research.google.com/github/prerit2010/ML-Codes/blob/main/addition_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# generate a list numbers between 0 and 10000
a = np.arange(0, 10000, 1)

In [ ]:
# create the dataset for addition of numbers (10000 data points)
data = []
label = []
for i in range(0,10000):
    x = np.random.choice(a, 2)
    y = x[0] + x[1]
    data.append(x)
    label.append(y)
data = np.array(data)
label = np.array(label)

In [ ]:
data.shape, label.shape

((10000, 2), (10000,))

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, label, random_state=1)

In [ ]:
regr = LinearRegression().fit(X_train, y_train)
regr.predict(X_test[:2]), y_test[:2]

(array([12215., 10103.]), array([12215, 10103]))

In [ ]:
regr = MLPRegressor(random_state=1, max_iter=1000).fit(X_train, y_train)
regr.predict(X_test[:2]), y_test[:2]

(array([12214.63070007, 10103.75403573]), array([12215, 10103]))

In [ ]:
# through keras
from tensorflow import keras

In [ ]:
model = keras.Sequential()
model.add(keras.layers.Dense(1, name="layer1"))

In [ ]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
model.fit(X_train, y_train, epochs=1000)

Epoch 1/1000
235/235 [==============================] - 1s 3ms/step - loss: 0.0110
Epoch 2/1000
235/235 [==============================] - 1s 2ms/step - loss: 0.0672
Epoch 3/1000
235/235 [==============================] - 1s 3ms/step - loss: 0.0198
Epoch 4/1000
235/235 [==============================] - 1s 3ms/step - loss: 0.3268
Epoch 5/1000
235/235 [==============================] - 0s 2ms/step - loss: 0.0687
Epoch 6/1000
235/235 [==============================] - 1s 2ms/step - loss: 0.0641
Epoch 7/1000
235/235 [==============================] - 1s 3ms/step - loss: 0.1999
Epoch 8/1000
235/235 [==============================] - 1s 2ms/step - loss: 0.4072
Epoch 9/1000
235/235 [==============================] - 0s 2ms/step - loss: 0.2592
Epoch 10/1000
235/235 [==============================] - 0s 1ms/step - loss: 0.0011
Epoch 11/1000
235/235 [==============================] - 0s 1ms/step - loss: 0.0015
Epoch 12/1000
235/235 [==============================] - 0s 1ms/step - loss: 0.0113
E

KeyboardInterrupt: ignored

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(X_test[:5]), y_test[:5]

(array([[12215.],
        [10103.],
        [12421.],
        [ 8814.],
        [11301.]], dtype=float32), array([12215, 10103, 12421,  8814, 11301]))